backend:
  name: git-gateway
  branch: main  # Adjust if your main branch is named differently

media_folder: "image"  # Where images are stored in the repo
public_folder: "/image"  # Path to access images on the site



collections:
  - name: "highlights"
    label: "Highlights"
    files:
      - file: "data/highlights.json"  
        label: "Highlights"
        name: "highlights"
        fields:
          - label: "Highlights"
            name: "highlights"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Href", name: "href", widget: "string" }

  - name: "novels"
    label: "Novels"
    files:
      - file: "data/novels.json"
        label: "Novels"
        name: "novels"
        fields:
          - label: "Novels"
            name: "novels"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - {
                  label: "Short Description",
                  name: "shortDescription",
                  widget: "text",
                }
              - {
                  label: "Long Description",
                  name: "longDescription",
                  widget: "text",
                }
              - { label: "Image", name: "image", widget: "image" }

  - name: "projects"
    label: "Projects"
    files:
      - file: "data2/projects.json"
        label: "Projects"
        name: "projects"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

  - name: "news1"
    label: "PFBS News "
    files:
      - file: "data2/news1.json"
        label: "News 1"
        name: "newsList"
        fields:
          - label: "News 1"
            name: "newsList"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Short Description", name: "shortDescription", widget: "text" }
              - { label: "Long Description", name: "longDescription", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

  - name: "news2"
    label: "News & Updates"
    files:
      - file: "data2/news2.json"
        label: "News 2"
        name: "newsList"
        fields:
          - label: "News 2"
            name: "newsList"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Short Description", name: "shortDescription", widget: "text" }
              - { label: "Long Description", name: "longDescription", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

  - name: "slider1"
    label: "Family Image VR Ajith"
    files:
      - file: "data2/familyimage1.json"
        label: "Family Image 1"
        name: "slider1"
        fields:
          - label: "Family Image 1"
            name: "slider1"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }

  - name: "slider2"
    label: "Family Image L Jayasree "
    files:
      - file: "data2/familyimage2.json"
        label: "Family Image 2"
        name: "slider2"
        fields:
          - label: "Family Image 2"
            name: "slider2
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }

  - name: "familyvideo1"
    label: "Family Video 1"
    files:
      - file: "data2/familyvideo1.json"
        label: "Family Video 1"
        name: "familyvideo1"
        fields:
          - label: "Family Video 1"
            name: "familyvideo1"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL", name: "videoUrl", widget: "string" }

  - name: "familyvideo2"
    label: "Family Video 2"
    files:
      - file: "data2/familyvideo2.json"
        label: "Family Video 2"
        name: "familyvideo2"
        fields:
          - label: "Family Video 2"
            name: "familyvideo2"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL", name: "videoUrl", widget: "string" }

  - name: "imagegallery"
    label: "Image Gallery"
    files:
      - file: "data2/imagegallery.json"
        label: "Image Gallery"
        name: "imagegallery"
        fields:
          - label: "Image Gallery"
            name: "imagegallery"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image URL", name: "imageUrl", widget: "string" }

  - name: "videogallery"
    label: "Video Gallery"
    files:
      - file: "data2/videogallery.json"
        label: "Video Gallery"
        name: "videogallery"
        fields:
          - label: "Video Gallery"
            name: "videogallery"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Video URL", name: "videoUrl", widget: "string" }

  - name: "articles"
    label: "Articles"
    files:
      - file: "data/articles.json"
        label: "Articles"
        name: "articles"
        fields:
          - label: "Articles List"
            name: "articles"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Short Description", name: "shortDescription", widget: "text" }
              - { label: "Long Description", name: "longDescription", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

  - name: "short-stories"
    label: "Short Stories"
    files:
      - file: "data/short-stories.json"
        label: "Short Stories"
        name: "short-stories"
        fields:
          - label: "Short Stories List"
            name: "short-stories"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Short Description", name: "shortDescription", widget: "text" }
              - { label: "Long Description", name: "longDescription", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

  - name: "travelogues"
    label: "Travelogues"
    files:
      - file: "data/travelogues.json"
        label: "Travelogues"
        name: "travelogues"
        fields:
          - label: "Travelogues List"
            name: "travelogues"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Short Description", name: "shortDescription", widget: "text" }
              - { label: "Long Description", name: "longDescription", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

  - name: "childrens-writing"
    label: "Children's Writing"
    files:
      - file: "data/childrens-writing.json"
        label: "Children's Writing"
        name: "childrens-writing"
        fields:
          - label: "Children's Writing List"
            name: "childrens-writing"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Short Description", name: "shortDescription", widget: "text" }
              - { label: "Long Description", name: "longDescription", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }


