backend:
  name: git-gateway
  branch: main  # Adjust if your main branch is named differently

media_folder: "image"  # Where images are stored in the repo
public_folder: "/image"  # Path to access images on the site



collections:
  - name: "highlights"
    label: "Highlights"
    files:
      - file: "data/highlights.json"  
        label: "Highlights"
        name: "highlights"
        fields:
          - label: "Highlights"
            name: "highlights"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Href", name: "href", widget: "string" }

  - name: "novels"
    label: "Novels"
    files:
      - file: "data/novels.json"
        label: "Novels"
        name: "novels"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Short Description", name: "shortDescription", widget: "text" }
          - { label: "Long Description", name: "longDescription", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }

  - name: "projects"
    label: "Projects"
    files:
      - file: "data2/projects.json"
        label: "Projects"
        name: "projects"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }

  - name: "news1"
    label: "News 1"
    files:
      - file: "data2/news1.json"
        label: "News 1"
        name: "news1"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }

  - name: "news2"
    label: "News 2"
    files:
      - file: "data2/news2.json"
        label: "News 2"
        name: "news2"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }

  - name: "familyimage1"
    label: "Family Image 1"
    files:
      - file: "data2/familyimage1.json"
        label: "Family Image 1"
        name: "familyimage1"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }

  - name: "familyimage2"
    label: "Family Image 2"
    files:
      - file: "data2/familyimage2.json"
        label: "Family Image 2"
        name: "familyimage2"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }

  - name: "familyvideo1"
    label: "Family Video 1"
    files:
      - file: "data2/familyvideo1.json"
        label: "Family Video 1"
        name: "familyvideo1"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Video URL", name: "videoUrl", widget: "string" }

  - name: "familyvideo2"
    label: "Family Video 2"
    files:
      - file: "data2/familyvideo2.json"
        label: "Family Video 2"
        name: "familyvideo2"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Video URL", name: "videoUrl", widget: "string" }

  - name: "imagegallery"
    label: "Image Gallery"
    files:
      - file: "data2/imagegallery.json"
        label: "Image Gallery"
        name: "imagegallery"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image URL", name: "imageUrl", widget: "string" }

  - name: "videogallery"
    label: "Video Gallery"
    files:
      - file: "data2/videogallery.json"
        label: "Video Gallery"
        name: "videogallery"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Video URL", name: "videoUrl", widget: "string" }

