backend:
  name: git-gateway
  branch: main  # Adjust if your main branch is named differently

media_folder: "image"  # Where images are stored in the repo
public_folder: "/image"  # Path to access images on the site



collections:
  - name: "highlights"
    label: "Highlights"
    files:
      - file: "data/highlights.json"  
        label: "Highlights"
        name: "highlights"
        fields:
          - label: "Highlights"
            name: "highlights"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Href", name: "href", widget: "string" }




  - name: "novels"
    label: "Novels"
    files:
      - file: "data/novels.json"
        label: "Novels"
        name: "novels"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Short Description",
              name: "shortDescription",
              widget: "text",
            }
          - {
              label: "Long Description",
              name: "longDescription",
              widget: "text",
            }
          - { label: "Image", name: "image", widget: "image" }

  - name: "projects"
    label: "Projects"
    folder: "data2"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "news1"
    label: "News 1"
    folder: "data2"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "news2"
    label: "News 2"
    folder: "data2"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "familyimage1"
    label: "Family Image 1"
    folder: "data2"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "familyimage2"
    label: "Family Image 2"
    folder: "data2"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "familyvideo1"
    label: "Family Video 1"
    folder: "data2"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Video URL", name: "videoUrl", widget: "string" }

  - name: "familyvideo2"
    label: "Family Video 2"
    folder: "data2"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Video URL", name: "videoUrl", widget: "string" }

  - name: "imagegallery"
    label: "Image Gallery"
    folder: "data2"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image URL", name: "imageUrl", widget: "string" }

  - name: "videogallery"
    label: "Video Gallery"
    folder: "data2"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Video URL", name: "videoUrl", widget: "string" }
